# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aee858fe977f90d1ef21a4c819bfae735359edb663fb9362cff2d4cf55f8f367f7118b2e894b0e352d409dea7dbc7a61eea9dcfc4ede0b355c53e83c55122700

test:
  secret_key_base: 43e75078a7aad273195bc0c06c22d22481d75740f9484ad4632d3dca5040330c89d7328a44ee3bef20f2a71ffcfea56f5f474dae4457b06437b35281baed0f24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
